- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:bruno-gurgel/.dotfile.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
