- name: Install Zsh
  become: true
  apt: name=zsh
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags:
    - zsh
- name: Install the zsh plugin autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
- name: Install the zsh plugin zsh-z
  ansible.builtin.git:
    repo: 'https://github.com/agkozak/zsh-z'
    dest: "~/.oh-my-zsh/plugins/zsh-z"
  tags:
    - zsh
- name: Install the zsh plugin syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
    - zsh
- name: Update our zshrc
  ansible.builtin.replace:
    path: ~/.zshrc
    regexp: '\(git'
    replace: '(git zsh-autosuggestions zsh-z zsh-syntax-highlighting'
  tags:
    - zsh
